# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{cookie_domains}
  s.version = ""

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jakub Kosi\305\204ski"]
  s.date = %q{2010-01-28}
  s.description = %q{Cookie domains is a Rails plugin and Rack middleware to setting cookies in mutli-domain environment. Define domains for your applications and set correct cookie based on request hostname.}
  s.email = %q{ja@ghandal.net}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "MIT-LICENSE",
     "README",
     "Rakefile",
     "VERSION",
     "cookie_domains.gemspec",
     "install.rb",
     "lib/cookie_domains.rb",
     "spec/cookie_domains_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/ghandal/cookie_domains}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Rack middleware for setting cookies in Rails applications based on request host}
  s.test_files = [
    "spec/cookie_domains_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_development_dependency(%q<action_controller>, [">= 2.3"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<action_controller>, [">= 2.3"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<action_controller>, [">= 2.3"])
  end
end

